apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . | default (printf "%s-%s" .Release.Name "myapp") }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
