replicaCount: 2

image:
  # GitHub Actions will replace this with: ghcr.io/<owner>/<repo>
  repository: ghcr.io/fedor-afrin/myapp-gitops
  tag: "aa6cf92"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
